### ISSUE TITLE
Race condition: We had to kill ffmpeg to stop it.

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [imageio/imageio-ffmpeg#13] opened 2019-03-24 12:50 UTC
I'm trying to encode several `mp4`s at a time, and all of the larger ones give me the message `We had to kill ffmpeg to stop it.` Most of the files for which this message is printed are corrupted. Looking at the code, there appears to be a race condition in there where it only gives `ffmpeg` 2.5s to clean up. Is this needed? Or is there a way to disable that?

**Comment by almarklein** [comment] 2019-03-24 20:40
It is a safety check to prevent runaway ffmpeg processes. The 2.5 seconds is somewhat arbitrary. It was assumed to be enough. Is it likely that in your case ffmpeg would finish by itself, and if so, could we perhaps consider a more reasonable timeout?

**Comment by TinyTheBrontosaurus** [comment] 2019-03-24 21:52
in my test case i had about 500 videos i was trying to encode and 400 of them were corrupted with this message. I went in and disabled the timeout and all 500 of the succeeded. I'm running in a scenario where the CPU will frequently become starved due to other things going on and that's why it's hitting the timeout. 

If this runaway `ffmpeg` check is done with a timeout, it will by definition always be a race condition that will frequently occur on resource constrained systems. But I guess I don't fully understand in what cases `ffmpeg` is out of control to give a better idea of how to remove the race condition.

**Comment by TinyTheBrontosaurus** [comment] 2019-03-25 02:20
As a workaround, i'm current adding this to my code:
```
with mock.patch("imageio_ffmpeg._io.subprocess.Popen.kill"):
```

**Comment by TinyTheBrontosaurus** [comment] 2019-03-25 02:46
more info: my latest run (before i implemented the workaround above) was on my MacBook Pro (2015, High Sierra, py3.7) and it still corrupted the video. Created a 1600x2000 resolution video with 3600 frames. Nothing else significant was running on my computer.

**Comment by almarklein** [comment] 2019-03-25 08:11
Ok, so this applies to writing a video, correct? I suppose what's happening is that Python fills up the buffer (stdin for ffmpeg) and ffmpeg is unable to process all frames in time. Perhaps reducing the size of this buffer will help ensure that ffmpeg can (nearly) always process the frames in time.

An additional/alternative option could be to add an option to skip this kill step.

**Comment by TinyTheBrontosaurus** [comment] 2019-03-25 12:40
Yes, it is only for writing. i'm having no issues on the read side.

**Comment by jmetz** [comment] 2019-04-02 14:02
I've just run into this issue in a pretty lightweight scenario (low frame count - `35`, but large input frame size of `2048x2048`).

I upped the timeout to 10s, during which `ffmpeg` closed normally. 

This is on the following machine

    Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux

It is *not* a particularly low-spec machine (8 cores, 32GB RAM).

**Comment by almarklein** [comment] 2019-04-03 11:55
If someone wants to have a go at this before I find the time to do so: I think we should try to lower the buffer size of stdin when we open the subprocess, and see if this helps.

**Comment by jmetz** [comment] 2019-04-03 12:05
> If someone wants to have a go at this before I find the time to do so: I think we should try to lower the buffer size of stdin when we open the subprocess, and see if this helps.

Does that make sense given that increasing the timeout allows it to close? Is the buffer being filled with more data in that extra time allowing it to be flushed?

**Comment by almarklein** [comment] 2019-04-03 12:19
Python fills up the buffer with frames, and ffmpeg consumes them. Python will slow down if ffmpeg consumes frames slower than Python adds them. When Python is done, it waits for ffmpeg to finish. So if the buffer is considerably smaller (but large enough to fit at least say 5 frames) then the wait for Python should be negligible (well that's my theory).

**Comment by jmetz** [comment] 2019-04-03 12:22
Ah I think I see what you mean - should be a fairly easy thing to test anyway. Might have time this weekend if no-one has a stab at it.

**Comment by TinyTheBrontosaurus** [comment] 2019-04-03 12:28
I don't have a great understanding of the issue that causes the kill
command to be needed at all. can anyone give more info about how to repro
that? I've been able to code thousands of videos without issue by removing
the kill

**Comment by almarklein** [comment] 2019-04-03 12:36
We've had reports in earlier versions (in imageio) of daemon ffmpeg processes. Although the chance of this happening is way larger with reading from ffmpeg, I still very much like the idea that one can rely on the fact that ffmpeg has stopped when the generator exits. Even if ffmpeg finishes eventually, you may end up with many ffmpeg processes that compete for resources.

**Comment by TinyTheBrontosaurus** [comment] 2019-04-04 23:04
are there any repros for the read issue? I'm doing a lot of reading as well and haven't seen the message printed

**Comment by almarklein** [comment] 2019-04-05 09:41
I think that this issue applies mostly to writing. When reading, Python first asks ffmpeg to stop and then waits for it do so. There is no buffer to process first. It's good to hear that you've not seen the message: it means that the way that we tell ffmpeg to stop is working well :)

**Comment by jmetz** [comment] 2019-04-05 15:35
I can confirm that for me this *only happens for very large input frames*. 
I tested with original size frames (read from jpg images) of size `2048x2048`, and the issue was present and required a larger timeout. 

Then I tested for half size images (`1024x1024`) and the issue disappears.

Just gonna see if I can narrow in on the size that this first crops up at.

**Comment by jmetz** [comment] 2019-04-05 15:58
On my machine, the approximate size at which this occurs (it's not 100% consistent), is 
between `1864, 1864` and `1884, 1884`, both of which also result in `swscaler` warnings as well as an automatic alignment to the 16bit block size. These warnings also occur at lower sizes which don't result in the 

    We had to kill ffmpeg to stop it.

issue. 

IMO, at least as far as it pertains to my situation, this issue is entirely due to FFMPEG just not being able to finalize within the `2.5s` allocated window for very large frames. 

Given that the  process is polled at a `0.01` second interval anyway, I would recommend that the simplest solution would be to simply increase the timeout to e.g. `5s` in order to accommodate situations with very large frame sizes. 

There should be absolutely no affect on smaller frame sizes, and at worst if an actual hang occurs, the process is just killed a little later.

**Comment by jmetz** [comment] 2019-04-05 16:27
Simple modification to the included `imageio-ffmpeg` tests to reproduce: 

```python
import numpy as np

...

def test_write_big_frames():

    sizes = []
    for pixfmt, bpp in [("gray", 1), ("rgb24", 3), ("rgba", 4)]:
        # Prepare for writing
        gen = imageio_ffmpeg.write_frames(
            test_file2, (2048, 2048), pix_fmt_in=pixfmt)
        gen.send(None)  # seed
        for i in range(9):
            data = bytes((255 * np.random.rand(2048 * 2048 * bpp)).astype(int))
            gen.send(data)
        gen.close()
        with open(test_file2, "rb") as f:
            sizes.append(len(f.read()))
        # Check nframes
        nframes, nsecs = imageio_ffmpeg.count_frames_and_secs(test_file2)
        assert nframes == 9
```

**Comment by djhoese** [comment] 2019-04-10 13:14
I've been running in to this a lot lately when trying to generate mp4s of satellite instrument data. Is there currently a workaround for this? If not, would a keyword argument be possible?

**Comment by jmetz** [comment] 2019-04-10 13:22
> I've been running in to this a lot lately when trying to generate mp4s of satellite instrument data. Is there currently a workaround for this? If not, would a keyword argument be possible?

Yes - you can set the timeout to a higher value. 
I.e. line 424 in `_io.py` (https://github.com/imageio/imageio-ffmpeg/blob/master/imageio_ffmpeg/_io.py#L424), increase the hard-coded 2.5 up to 10.0 or similar. 

As a proposed fix, I would suggest setting this value via a `kwarg` such that `write_frames` can be specifically called with a higher timeout to avoid this issue.

**Comment by djhoese** [comment] 2019-04-10 13:36
Ok I can add this and make a PR. Would `timeout` be a little too generic? Maybe `ffmpeg_timeout`?

**Comment by jmetz** [comment] 2019-04-10 13:38
> Ok I can add this and make a PR. Would `timeout` be a little too generic? Maybe `ffmpeg_timeout`?

Yes - I'd also go with `ffmpeg_timeout` I think :+1:

**Comment by djhoese** [comment] 2019-04-10 15:07
@jmetz I tried adding your test to `test_io.py` and it is telling me that it's producing `72` frames instead of `9`. Any ideas?

**Comment by djhoese** [comment] 2019-04-10 16:33
Nevermind, I got the test to pass (see #14) by forcing the dtype to uint8.

**Comment by TinyTheBrontosaurus** [comment] 2019-04-10 17:50
re workaround, what i posted above has worked fine for me (though it doesn't clutter the code) https://github.com/imageio/imageio-ffmpeg/issues/13#issuecomment-476032276
```
with mock.patch("imageio_ffmpeg._io.subprocess.Popen.kill"):
```

that completely eliminates the race condition by removing the kill.

**Comment by djhoese** [comment] 2019-04-10 17:52
@TinyTheBrontosaurus IMO this is not a sustainable solution. Users should not have to mock a library to use it as advertised. Mocking should be reserved for testing. I think my pull request linked above is the best long term solution.

**Comment by TinyTheBrontosaurus** [comment] 2019-04-10 18:02
agreed. 

I re-posted because someone requested a workaround, which typically aren't long-term solutions. This can be added without waiting for a PR to get approved, merged, released and posted.

**Comment by almarklein** [comment] 2019-04-12 08:54
Fixed by #14 and #15.

**Closed by almarklein** 2019-04-12 08:54 UTC

**Comment by almarklein** [comment] 2019-04-12 09:12
A new release is now available on Pypi.

**Comment by almarklein** [comment] 2019-04-12 20:09
(and I just updated the feedstock too)

**Comment by mdimranuddin** [comment] 2019-07-14 15:43
I have also face this problem. After 67 percent-encode in my video then this error message shown. How can fix this?
error is : "We had to kill ffmpeg to stop it. Consider increasing ffmpeg_timeout."

**Comment by TinyTheBrontosaurus** [comment] 2019-07-14 17:02
did you try increasing the `ffmpeg_timeout`? it's an argument to `imageio_ffmpeg.write_frames`

**Comment by djhoese** [comment] 2019-07-14 22:59
@mdimranuddin What version of `imageio` are you using? If you are using anything older than 2.5.0 then this error/warning is much more likely to happen. Otherwise, try `ffmpeg_timeout` as @TinyTheBrontosaurus has suggested.

**Comment by mdimranuddin** [comment] 2019-07-19 07:01
@djhoese @TinyTheBrontosaurus  Thank you, sir, both of you. I'm used, anaconda navigator environment, Spider IDE. I've also used the latest version of "imageio" 2.5.0. Finally, I'm increasing the "ffmpeg_timeout", then It's working smoothly. But it's slowly working because of my RAM. But finally It's working, Again Thanks to both of you.

**Comment by OrganicIrradiation** [comment] 2019-08-22 16:29
I'm receiving this warning when using ```imageio.get_writer()``` and ```writer.append_data()```. How would I go about passing ```ffmpeg_timeout``` to increase (or ignore) the timeout?

**Comment by djhoese** [comment] 2019-08-22 16:31
@OrganicIrradiation What version of imageio are you using? Are you writing excessively large frames? I believe `ffmpeg_timeout` can be passed to `append_data` iirc.

**Comment by OrganicIrradiation** [comment] 2019-08-22 16:36
@djhoese v2.5.0 from PyPi.

I just took a look at https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py and ```_initialize()``` does not include a method of parsing ffmpeg_timeout nor does ```_append_data()```. I confirmed by adding ```ffmpeg_timeout=0``` to the ```imageio.get_writer()``` init, the ```writer.append_data()``` call, and to the ```writer.close()```. All gave me a ```unexpected keyword argument 'ffmpeg_timeout'``` exception.

**Comment by djhoese** [comment] 2019-08-22 16:59
You are right. The new default timeout just happened to be good enough for most people. I'm curious what size data you are writing that is hitting that timeout?

Anyway, if you'd like to make a pull request I think you would have to add the option to `_open` and then pass it along after that: https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py#L247-L258

**Comment by OrganicIrradiation** [comment] 2019-08-22 17:23
@djhoese I've temporarily changed my ```imageio.``` commands to ```imageio_ffmpeg.``` to allow for the timeout. Regarding the data size, I'm not sure where the problem is arising, since the timeout is not raising an exception and the warning is shown in the middle of my script. I'll try to investigate further, but this is a temporary work-around.

**Comment by rmahtoa** [comment] 2024-10-25 05:44
Maybe this can help
https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg
